[package]
name = "themeswitch-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = { version = "1.1.6", features = ["serde"] }
clap = { version = "4.5.3", features = ["derive", "cargo"] }
config = "0.14.0"
fs_extra = "1.3.0"
home = "0.5.9"
lazy_static = "1.4.0"
minijinja = "1.0.16"
once_cell = "1.19.0"
regex = "1.10.4"
scopeguard = "1.2.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
toml = "0.8.12"
